version: "3.7"

services:
  api:
    build: infoportal_app/
    restart: always
    volumes:
      - ./infoportal_app:/app
      - static_web:/app/static

    environment:
      - ENV=prod
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      - db
  admin:
    build: admin_app/
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
       - .env
    expose:
      - "5432"

volumes:
  postgres_db:
  static_web:
