"""initial

Revision ID: 416ce862261f
Revises: 
Create Date: 2022-12-19 20:19:55.644179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416ce862261f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pswd', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
